# Generated by Django 3.2.25 on 2025-06-26 16:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('musicbeats', '0008_like'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Like',
        ),
    ]
