# Generated by Django 3.2.25 on 2025-07-10 08:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('musicbeats', '0011_podcast'),
    ]

    operations = [
        migrations.AddField(
            model_name='history',
            name='song',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='musicbeats.song'),
        ),
    ]
