# Generated by Django 3.2.25 on 2025-07-10 16:57

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('musicbeats', '0012_history_song'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='history',
            name='music_id',
        ),
        migrations.AddField(
            model_name='history',
            name='timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='history',
            name='song',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='musicbeats.song'),
        ),
    ]
