# Generated by Django 3.2.25 on 2025-07-10 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musicbeats', '0013_auto_20250710_2227'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='history',
            name='song',
        ),
        migrations.RemoveField(
            model_name='history',
            name='timestamp',
        ),
        migrations.AddField(
            model_name='history',
            name='music_id',
            field=models.CharField(default='', max_length=10000000),
        ),
    ]
