# Generated by Django 3.2.25 on 2025-09-05 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musicbeats', '0014_auto_20250710_2231'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='cover_art',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
