# Generated by Django 3.2.25 on 2025-09-05 08:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('musicbeats', '0015_song_cover_art'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='song',
            name='cover_art',
        ),
    ]
